### ISSUE TITLE
Test dla Trello

### ISSUE THREAD

**Issue by witoldb** [witoldb/TPD_02#2]
Testowy dla ttrello

**Comment by sokolpsycho** [comment]
???

**Comment by witoldb** [comment]
Testuje integrację między trello a github.
25 kwi 2015 23:23 "sokolpsycho" notifications@github.com napisał(a):

**Comment by sokolpsycho** [comment]
Ok a ja się ostro zabrałem za bootstrapa i składam stronę główną.

**Comment by witoldb** [comment]
Spoko :)
Jutro się pochwalisz.
Zamykam testowy.
